# Generated by Django 4.1 on 2022-09-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The Price must be between 9 and 999.99'}}, help_text='Maximum 999.99', max_digits=6, verbose_name='Discont Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The Price must be between 9 and 999.99'}}, help_text='Maximum 999.99', max_digits=6, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.product'),
        ),
    ]
