# Generated by Django 4.0.3 on 2022-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.CharField(blank=True, help_text='Not Required', max_length=100, null=True, verbose_name='Headline'),
        ),
    ]
