# Generated by Django 4.0.3 on 2022-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_featured1_product_featured2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Required', max_length=250, verbose_name='Type Name '),
        ),
    ]
