# Generated by Django 4.0.3 on 2023-03-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
