# Generated by Django 4.0.3 on 2023-03-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productspecification'),
        ),
    ]
