# Generated by Django 4.0.3 on 2023-03-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_specs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='store.product'),
        ),
    ]
