# Generated by Django 4.0.3 on 2023-03-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_bkd',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
