export const ADD_SHIPPING  = 'ADD_SHIPPING'
export const ADD_PAYMENT = 'ADD_PAYMENT'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL= 'ADD_ORDER_FAIL'

export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL= 'ORDER_FAIL'
export const ORDER_RESET= 'ORDER_RESET'

export const ORDER_DETAILS = 'ORDER_DETAILS'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL= 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET= 'ORDER_DETAILS_RESET'

export const SHIPPING_RESET = 'SHIPPING_RESET'
export const PAYMENT_RESET = 'PAYMENT_RESET'