export const RATE_PRODUCT = 'REVIEW_PRODUCT'
export const RATE_PRODUCT_SUCCESS = 'RATE_PRODUCT_SUCCESS'
export const RATE_PRODUCT_FAIL= 'RATE_PRODUCT_FAIL'

export const REVIEW_PRODUCT = 'REVIEW_PRODUCT'
export const REVIEW_PRODUCT_SUCCESS = 'REVIEW_PRODUCT_SUCCESS'
export const REVIEW_PRODUCT_FAIL= 'REVIEW_PRODUCT_FAIL'

export const VIEW_REVIEWS = 'VIEW_REVIEWS'
export const VIEW_REVIEWS_SUCCESS = 'VIEW_REVIEWS_SUCCESS'
export const VIEW_REVIEWS_FAIL= 'VIEW_REVIEWS_FAIL'
export const VIEW_REVIEWS_RESET = 'VIEW_REVIEWS_RESET'