export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL= 'LOGIN_FAIL'

export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'

export const EDIT_PASSWORD_USER = 'EDIT_PASSWORD_USER'
export const EDIT_PASSWORD_USER_SUCCESS = 'EDIT_PASSWORD_USER_SUCCESS'
export const EDIT_PASSWORD_USER_FAIL = 'EDIT_PASSWORD_USER_FAIL'

export const DETAILS_USER = 'DETAILS_USER'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL= 'DETAILS_FAIL'
export const DETAILS_USER_RESET = 'DETAILS_USER_RESET'

export const ORDERS_USER = 'ORDERS_USER'
export const ORDERS_USER_SUCCESS = 'ORDERS_USER_SUCCESS'
export const ORDERS_USER_FAIL= 'ORDERS_USER_FAIL'
export const ORDERS_USER_RESET = 'ORD_USER_RESET'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAIL= 'USERS_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'