# Generated by Django 4.0.3 on 2023-01-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_discount_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_ccno',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_exp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
