# Generated by Django 4.0.3 on 2023-03-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_ordershipping_user_ordershipping_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipping',
            name='address2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
