# Generated by Django 4.0.3 on 2023-03-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_ordershipping_order_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
