# Generated by Django 4.0.3 on 2023-03-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_deliverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_ccno',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_exp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
